---
- name: Install the packages
  ansible.builtin.import_playbook: playbooks/install-packages.yml
- name: Register data 
  ansible.builtin.import_playbook: playbooks/register-data.yml
- name: Configure replication 
  ansible.builtin.import_playbook: playbooks/configure-replication.yml
    